# -*- coding: utf-8 -*-
"""face_recognition library

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eVuLDWbZmrjQE2B9umFLO6xZz4i09R3r
"""

!pip install face_recognition

!mkdir known
!wget http://mydiba.me/wp-content/uploads/actors/Park-Hye-su.jpg -O known/parkhyesu.jpg
!wget https://api.duniagames.co.id/api/content/upload/file/19876251281578066786.jpg -O known/vanda.jpg
!wget https://upload.wikimedia.org/wikipedia/commons/e/e4/Chelsea_Islan%2C_2019.jpg -O known/chelseaislan.jpg

!mkdir unknown
!wget https://wallpapercave.com/wp/wp2102679.jpg -O unknown/1.jpg
!wget https://kpoplat.com/wp-content/uploads/2020/11/park-shie.jpg -O unknown/2.jpg
!wget https://i.pinimg.com/originals/ef/a8/47/efa847e5d45b98c2bd6d631b96671c5a.jpg -O unknown/3.jpg
!wget https://www.celebritiesfrom.com/wp-content/uploads/2019/07/kim-so-hyun1.jpg -O unknown/4.jpg

# Import Library needed
import face_recognition
import os
import cv2
from google.colab.patches import cv2_imshow

def read_img(path):
  img = cv2.imread(path)
  (h,w) = img.shape[:2]
  weight = 500
  ratio = weight / float(w)
  height = int(h*ratio)
  final = cv2.resize(img, (weight, height))
  return final

import random

known_names = []
known_encoding = []
known_dir = 'known'

for file in os.listdir(known_dir):
  img = read_img(known_dir + '/' + file)
  img_enc = face_recognition.face_encodings(img)[0]
  known_encoding.append(img_enc)
  known_names.append(file.split('.')[0])

unknown_names = []
unknown_encoding = []
unknown_dir = 'unknown'

for f in os.listdir(unknown_dir):
  print('Processing', f)
  img = read_img(unknown_dir + '/' + f)
  img_enc = face_recognition.face_encodings(img)[0]

  result = face_recognition.compare_faces(known_encoding, img_enc)
  print(result)
  distance = face_recognition.face_distance(known_encoding, img_enc)
  print(distance)
  # print(distance.min())
  min_dist = distance[0]
  index = 0
  for i, dis in enumerate(distance):
    if dis < min_dist:
      min_dist = dis
      index = i
  print('Index :', index, '\tMinimum Distance :', min_dist)
  name = known_names[index]
  (t, r, b, l) = face_recognition.face_locations(img)[0]
  cv2.rectangle(img, (l,t), (r,b), (255,0,0), 1)
  cv2.putText(img, name, (l+2,b+2),cv2.FONT_HERSHEY_PLAIN, 1, (255,255,255), 1)
  cv2_imshow(img)

  # for i in range(len(result)):
  #   if result[i]:
  #     name = known_names[i]
  #     (t, r, b, l) = face_recognition.face_locations(img)[0]
  #     cv2.rectangle(img, (l,t), (r,b), (255,0,0), 1)
  #     cv2.putText(img, name, (l+2,b+2),cv2.FONT_HERSHEY_PLAIN, 1, (255,255,255), 1)
  #     cv2_imshow(img)

